### ISSUE TITLE
Build Setup steps and tests fail

### ISSUE THREAD

**Issue by ferm10n** [eddyerburgh/vue-test-utils-ava-example#7]
Hello,

I am going through your example projects trying to find a test harness that works.

Following the build setup steps:
- `npm install`: ok
- `npm run dev`: fails
  - a webpage is opened (http://localhost:8080/) but gives a 404 `Cannot GET /`
  - this error is shown:
```
 ERROR  Failed to compile with 2 errors                                                                                                                                                                    3:11:34 PM

Module build failed: TypeError: sourceText.startsWith is not a function
    at Function.SourceCodeFixer.applyFixes (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint/lib/util/source-code-fixer.js:76:26)
    at Function.SourceCodeFixer.applyFixes (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint-plugin-html/src/index.js:151:23)
    at Linter.verifyAndFix (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint/lib/linter.js:1141:43)
    at processText (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint/lib/cli-engine.js:180:32)
    at CLIEngine.executeOnText (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint/lib/cli-engine.js:620:17)
    at lint (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint-loader/index.js:213:21)

Module build failed: TypeError: sourceText.startsWith is not a function
    at Function.SourceCodeFixer.applyFixes (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint/lib/util/source-code-fixer.js:76:26)
    at Function.SourceCodeFixer.applyFixes (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint-plugin-html/src/index.js:151:23)
    at Linter.verifyAndFix (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint/lib/linter.js:1141:43)
    at processText (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint/lib/cli-engine.js:180:32)
    at CLIEngine.executeOnText (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint/lib/cli-engine.js:620:17)
    at lint (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint-loader/index.js:218:17)
    at Object.module.exports (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/eslint-loader/index.js:213:21)

You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
> Listening at http://localhost:8080
```
  - removing the eslint-loader fixes this step and then the page can be viewed
- `npm run build`: suffers the same issues as `npm run dev`

- `npm run unit`: fails with this error:
```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'vue-test-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jsanders/Downloads/vue-test-utils-ava-example/test/specs/Message.spec.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at extensions.(anonymous function) (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
internal/modules/cjs/loader.js:638
    throw err;

Error: Cannot find module 'vue-test-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jsanders/Downloads/vue-test-utils-ava-example/test/specs/List.spec.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at extensions.(anonymous function) (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'vue-test-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/jsanders/Downloads/vue-test-utils-ava-example/test/specs/MessageToggle.spec.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at extensions.(anonymous function) (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jsanders/Downloads/vue-test-utils-ava-example/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

  3 exceptions

  ✖ test/specs/Message.spec.js exited with a non-zero exit code: 1

  ✖ test/specs/List.spec.js exited with a non-zero exit code: 1

  ✖ test/specs/MessageToggle.spec.js exited with a non-zero exit code: 1
```
  - this is despite the fact that vue-test-utils is found in node_modules

**Comment by ferm10n** [comment]
Oh, and node version is v10.16.0

**Comment by eddyerburgh** [comment]
Yes, this project is out of date, and it installed vue-test-utils from GitHub.

I've updated it to run if you use yarn:

```
yarn install && yarn unit
```
